DELETE FROM SID_REG_ENTIDAD_TIPO;

COMMIT;



Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('1', 'Centro médico');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('2', 'Colegio');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('3', 'Comisaría');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('4', 'BANCO DE MATERIALES (BANMAT)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('5', 'COLEGIOS PROFESIONALES');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('6', 'COMISION DE FORMALIZACION DE LA PROPIEDAD INFORMAL (COFOPRI)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('7', 'CONGRESO DE LA REPUBLICA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('8', 'CONSEJO NACIONAL DE LA MAGISTRATURA (CNM)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('9', 'CONTRALORIA GENERAL DE LA REPUBLICA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('10', 'DIRECCIONES REGIONALES DE EDUCACION');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('11', 'DIRECCIONES REGIONALES DE SALUD');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('12', 'EJERCITO DEL PERU (EP)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('13', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - CABLE');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('14', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - ELECTRICIDAD');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('15', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - GAS NATURAL');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('16', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - INTERNET');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('17', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - SANEAMIENTO');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('18', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - TELEFONIA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('19', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - TRANSPORTE TERRESTRE');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('20', 'ENTIDADES NO SUJETAS A SUPERVISION DIRECTA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('21', 'FONDO MIVIVIENDA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('22', 'FUERZA AEREA DEL PERU (FAP)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('23', 'GOBERNACIONES - MINISTERIO DEL INTERIOR');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('24', 'INSTITUTO NACIONAL PENITENCIARIO (INPE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('25', 'JURADO NACIONAL DE ELECCIONES (JNE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('26', 'MARINA DE GUERRA DEL PERU (MGP)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('27', 'MINISTERIO DE AGRICULTURA  (MINAG)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('28', 'MINISTERIO DE COMERCIO EXTERIOR Y TURISMO (MINCETUR)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('29', 'MINISTERIO DE CULTURA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('30', 'MINISTERIO DE DEFENSA (MINDEF)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('31', 'MINISTERIO DE DESARROLLO E INCLUSION SOCIAL (MIDIS)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('32', 'MINISTERIO DE ECONOMIA Y FINANZAS (MEF)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('33', 'MINISTERIO DE EDUCACION');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('34', 'MINISTERIO DE ENERGIA Y MINAS (MEM)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('35', 'MINISTERIO DE JUSTICIA (MINJUS)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('36', 'MINISTERIO DE LA MUJER Y DESARROLLO SOCIAL (MIMDES)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('37', 'MINISTERIO DE LA PRODUCCION (PRODUCE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('38', 'MINISTERIO DE RELACIONES EXTERIORES (RREE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('39', 'MINISTERIO DE SALUD');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('40', 'MINISTERIO DE TRABAJO Y PROMOCION DEL EMPLEO (MTPE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('41', 'MINISTERIO DE TRANSPORTES Y COMUNICACIONES (MTC)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('42', 'MINISTERIO DE VIVIENDA, CONSTRUCCION Y SANEAMIENTO (VIVIENDA)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('43', 'MINISTERIO DEL AMBIENTE (MINAM)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('44', 'MINISTERIO DEL INTERIOR (MININTER)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('45', 'MINISTERIO PUBLICO');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('46', 'MUNICIPALIDADES PROVINCIALES');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('47', 'OFICINA DE NORMALIZACION PREVISIONAL (ONP)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('48', 'OFICINA NACIONAL DE PROCESOS ELECTORALES (ONPE)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('49', 'OTROS');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('50', 'PODER JUDICIAL (PJ)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('51', 'POLICIA NACIONAL DEL PERU (PNP)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('52', 'PRESIDENCIA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('53', 'REGIONES');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('54', 'RENIEC');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('55', 'SEGURO SOCIAL DE SALUD (ESSALUD)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('56', 'SERVICIO DE AGUA POTABLE Y ALCANTARILLADO DE LIMA (SEDAPAL)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('57', 'SUPERINTENDENCIA NACIONAL DE BANCA Y SEGUROS (SBS)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('58', 'TELEFONICA DEL PERU - TELEFONIA');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('59', 'TRIBUNAL CONSTITUCIONAL (TC)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('60', 'UNIVERSIDADES');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('61', 'BANCO CENTRAL DE RESERVA (BCR)');
Insert into SID_REG_ENTIDAD_TIPO (N_ID_TIP,C_DETALLE) values ('62', 'EMPRESAS PRIVADAS PRESTADORAS DE SERVICIOS PUBLICOS - TRANSPORTE AEREO');



COMMIT;