UPDATE SIMCO_MAESTROS SET C_NOMBREPARAMETRO = 'Juzgado de paz' WHERE N_ID_PARAMETRO = 41;
UPDATE SIMCO_MAESTROS SET C_NOMBREPARAMETRO = 'ODECMA/OCMA (Organismo de Control de la Magistatura)' WHERE N_ID_PARAMETRO = 40;
UPDATE SIMCO_MAESTROS SET C_NOMBREPARAMETRO = 'Andino' WHERE N_ID_PARAMETRO = 112;
UPDATE SIMCO_MAESTROS SET C_NOMBREPARAMETRO = 'Amazónico' WHERE N_ID_PARAMETRO = 113;
commit;