--------------------------------------------------------
-- Archivo creado  - domingo-agosto-28-2016   
--------------------------------------------------------
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000001','COMISIONADO OD','ROL DE COMISIONADO OD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000002','SUPERVISOR OD','ROL DE SUPERVISOR OD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000003','COMISIONADO AD','ROL DE COMISIONADO AD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000004','SUPERVISOR AD','ROL DE SUPERVISOR AD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000005','PRACTICANTE OD','ROL DE PRACTICANTE OD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000006','PRACTICANTE AD','ROL DE PRACTICANTE AD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000007','COMISIONADO PAD','ROL DE COMISIONADO PAD','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000008','COMISIONADO OD - ONP','ROL DE COMISIONADO OD - ONP','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000009','OPERADOR - MANTENIMIENTO','ROL OPERADOR - MANTENIMIENTO','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000010','OBSERVADOR','OBSERVADOR','A');
Insert into SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000011','COMISIONADO OD-CAV','ROL DE COMISIONADO OD-CAV','A');

COMMIT;