CREATE VIEW VW_SEG_USUARIO
AS SELECT TRIM(A.USUARIO_USU) USUARIO_USU, A.NOMB_CORT_USU, A.TPIRCNE, 
B.APE_PAT_PER, B.APE_MAT_PER, B.NOM_EMP_PER, TRIM(B.LIBR_ELEC_PER) LIBR_ELEC_PER, B.SEX_EMP_PER,
D.C_CARGO, D.C_IDDEPARTAMENTO, D.C_RUTA, D.N_NIVEL, D.N_ID_OD
FROM SIGA.USUARIO A 
INNER JOIN SIGA.MAESTRO_PERSONAL B ON TRIM(SUBSTR(A.CODI_EMPL_PER,2)) = TRIM(B.CODI_EMPL_PER)
INNER JOIN SIGA.TDEPENDENCIAS C ON C.CODI_DEPE_TDE = A.CODI_DEPE_TDE
LEFT JOIN SID.SID_SEG_USUARIO D ON TRIM(A.USUARIO_USU) = TRIM(D.CODIGO_USUARIO);