Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('167','1','Tipo de infraestructura de transporte','1','0');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('168',null,'Ciclovías','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('169',null,'Veredas','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('170',null,'Pistas','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('171',null,'Estaciones de pasajeros y terminales','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('172',null,'Casetas de policía','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('173',null,'Rompemuelles o similares','2','167');
Insert into SID_REG_CLASIFICACION_TIPO (N_ID_CLASIFICACIONTIPO,N_ID_CLASIFICACION,C_DETALLE,N_NIVEL,N_PADRE) values ('174',null,'Semáforos','2','167');
COMMIT;