Insert into SID1.SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000007','COMISIONADO PAD','ROL DE COMISIONADO PAD','A');
Insert into SID1.SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000008','COMISIONADO OD - ONP','ROL DE COMISIONADO OD - ONP','A');
Insert into SID1.SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000009','OPERADOR - MANTENIMIENTO','ROL OPERADOR - MANTENIMIENTO','A');
Insert into SID1.SID_SEG_ROL (CODIGO_ROL,NOM_ROL,DES_ROL,COD_ESTADO) values ('ROL0000010','OBSERVADOR','OBSERVADOR','A');
COMMIT;